import { RespuestaImage } from "./respuesta-image.model";
import { RespuestaLegalidad } from "./respuesta-legalidad.model";
import { RespuestaPrecios } from "./respuesta-precios.model";


export interface RespuestaCarta{
  artist: string;
  artist_ids: string[];
  booster: boolean;
  border_color: string;
  card_back_id: string;
  cardmarket_id: number;
  cmc: number;
  collector_number: string;
  color_identity: string[];
  colors: string[];
  digital: boolean;
  edhrec_rank: number;
  finishes: string[];
  foil: boolean;
  frame: string;
  full_art: boolean;
  games: string[];
  highres_image: boolean;
  id: string;
  illustration_id: string;
  image_status: string;
  image_uris: RespuestaImage;
  keywords: string[];
  lang: string;
  layout: string;
  legalities: RespuestaLegalidad;
  mana_cost: string;
  mtgo_foil_id: number;
  mtgo_id: number;
  multiverse_ids: number[];
  name: string;
  nonfoil: boolean;
  object: string;
  oracle_id: string;
  oracle_text: string;
  oversized: boolean;
  penny_rank: number;
  prices: RespuestaPrecios;
  prints_search_uri: string;
  promo: boolean;
  //purchase_uris: PurchaseUris;
  rarity: string;
  //related_uris: RelatedUris;
  released_at: string;
  reprint: boolean;
  reserved: boolean;
  rulings_uri: string;
  scryfall_set_uri: string;
  scryfall_uri: string;
  set: string;
  set_id: string;
  set_name: string;
  set_search_uri: string;
  set_type: string;
  set_uri: string;
  story_spotlight: boolean;
  tcgplayer_id: number;
  textless: boolean;
  type_line: string;
  uri: string;
  variation: boolean;
}